(() => {
  const D = window.TAISELY_DATA || {articles:[],products:[],categories:[]};
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const page = document.body.dataset.page || '';
  const money = n => `$${Number(n).toFixed(2)}`;
  const get = (k, fallback) => { try { const v=localStorage.getItem(k); return v===null?fallback:JSON.parse(v); } catch { return fallback; } };
  const set = (k,v) => localStorage.setItem(k, JSON.stringify(v));
  const toast = (msg) => { const el=$('#toast'); if(!el)return; el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); };
  const visual = (kind,label='') => `<div class="visual ${kind||''}"><span>${label || kind || 'TAISELY'}</span></div>`;
  const articleCard = a => `<a class="card" href="article.html?id=${encodeURIComponent(a.id)}">${visual(a.image,a.category)}<div class="card-body"><div class="meta"><span>${a.category}</span><span>·</span><span>${a.type}</span><span>·</span><span>${a.reading}</span></div><h3 class="card-title">${a.title}</h3><p class="card-desc">${a.subtitle}</p></div></a>`;
  const miniArticle = a => `<a class="mini" href="article.html?id=${encodeURIComponent(a.id)}"><div class="meta"><span>${a.category}</span><span>·</span><span>${a.date}</span></div><h3 class="mini-title">${a.title}</h3><div class="muted" style="font-size:12px">${a.reading} read</div></a>`;
  const productCard = p => `<a class="card" href="product.html?id=${encodeURIComponent(p.id)}">${visual(p.image,p.category)}<div class="card-body"><div class="product-type">${p.format}</div><h3 class="card-title" style="font-size:22px">${p.name}</h3><div class="product-price">${money(p.price)}</div></div></a>`;
  function setupGlobal(){
    const theme = localStorage.getItem('taisely-theme') || 'dark';
    if(theme==='light') document.documentElement.style.setProperty('--bg','#f7f7f2');
    const themeBtn=$('[data-theme-toggle]');
    themeBtn?.addEventListener('click',()=>{
      const light = localStorage.getItem('taisely-theme')==='light';
      if(light){document.documentElement.style.setProperty('--bg','#050505');localStorage.setItem('taisely-theme','dark');document.body.style.color='var(--text)';}
      else {document.documentElement.style.setProperty('--bg','#f7f7f2');localStorage.setItem('taisely-theme','light');toast('Light mode enabled.');}
    });
    const menuBtn=$('[data-menu-toggle]'), panel=$('[data-menu-panel]');
    menuBtn?.addEventListener('click',()=>panel?.classList.toggle('open'));
    $$('form[data-newsletter]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault(); const em=f.querySelector('input').value.trim(); if(!em)return; set('taisely-newsletter',em); f.reset(); toast('Newsletter signup saved.');}));
  }
  function renderHome(){
    const featured=D.articles.find(a=>a.featured)||D.articles[0];
    const hero=$('#hero'); if(hero) hero.innerHTML=`<div class="hero-main">${visual(featured.image,featured.category)}<div class="hero-copy"><div class="meta"><span>${featured.type}</span><span>·</span><span>${featured.date}</span><span>·</span><span>${featured.reading}</span></div><h1 class="hero-title">${featured.title}</h1><p class="article-subtitle">${featured.subtitle}</p><div style="margin-top:18px"><a class="btn" href="article.html?id=${featured.id}">Read story</a></div></div></div><div class="hero-side"><div><div class="kicker">Now on TAISELY</div>${D.articles.slice(1,4).map(miniArticle).join('')}</div><div><div class="kicker">Explore</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px">${D.categories.map(c=>`<a class="pill" href="blog.html?category=${encodeURIComponent(c)}">${c}</a>`).join('')}</div></div></div>`;
    $('#latest') && ($('#latest').innerHTML=D.articles.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6).map(a=>`<div class="news-item"><a href="article.html?id=${a.id}">${visual(a.image,a.category)}</a><div><div class="meta"><span>${a.category}</span><span>·</span><span>${a.date}</span></div><a href="article.html?id=${a.id}"><h3 class="news-title">${a.title}</h3></a><p class="muted" style="margin:0;font-size:13px">${a.subtitle}</p></div></div>`).join(''));
    $('#technology') && ($('#technology').innerHTML=D.articles.filter(a=>a.category==='Technology').slice(0,3).map(articleCard).join(''));
    $('#energy') && ($('#energy').innerHTML=D.articles.filter(a=>a.category==='Energy').slice(0,3).map(articleCard).join(''));
    const deep=D.articles.find(a=>a.type==='Deep Dive')||D.articles[0];
    $('#deep-dive') && ($('#deep-dive').innerHTML=`<div class="feature-copy"><div class="kicker">Featured / Deep Dive</div><h3>${deep.title}</h3><p class="muted">${deep.subtitle}</p><div style="margin-top:22px"><a class="btn" href="article.html?id=${deep.id}">Open deep dive</a></div></div>${visual(deep.image,deep.category)}`);
    $('#most-read') && ($('#most-read').innerHTML=D.articles.slice().sort((a,b)=>b.readCount-a.readCount).slice(0,4).map((a,i)=>`<a class="card" href="article.html?id=${a.id}"><div class="card-body"><div class="meta"><span>#${i+1}</span><span>·</span><span>${a.readCount.toLocaleString()} reads</span></div><h3 class="card-title" style="font-size:21px">${a.title}</h3></div></a>`).join(''));
    $('#home-products') && ($('#home-products').innerHTML=D.products.slice(0,4).map(productCard).join(''));
  }
  function renderBlog(){
    const grid=$('#blog-grid'), cat=$('#category-filter'), type=$('#type-filter'), sort=$('#sort-filter'), search=$('#blog-search'); if(!grid)return;
    D.categories.forEach(c=>cat?.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));
    const params=new URLSearchParams(location.search); if(params.get('category'))cat.value=params.get('category');
    const run=()=>{let arr=[...D.articles]; const q=(search?.value||'').toLowerCase(); if(cat?.value)arr=arr.filter(a=>a.category===cat.value); if(type?.value)arr=arr.filter(a=>a.type===type.value); if(q)arr=arr.filter(a=>(a.title+' '+a.subtitle+' '+a.category).toLowerCase().includes(q)); if(sort?.value==='popular')arr.sort((a,b)=>b.readCount-a.readCount); else arr.sort((a,b)=>b.date.localeCompare(a.date)); grid.innerHTML=arr.length?arr.map(articleCard).join(''):`<div class="empty">No articles match these filters.</div>`;};
    [cat,type,sort,search].forEach(el=>el?.addEventListener('input',run)); run();
  }
  function renderArticle(){
    const id=new URLSearchParams(location.search).get('id')||D.articles[0].id; const a=D.articles.find(x=>x.id===id)||D.articles[0];
    $('#article').innerHTML=`<div class="article-header"><div class="meta"><span>${a.category}</span><span>·</span><span>${a.type}</span></div><h1>${a.title}</h1><p class="article-subtitle">${a.subtitle}</p><div class="article-meta"><span>By ${a.author}</span><span>·</span><span>${a.date}</span><span>·</span><span>${a.reading} read</span></div></div><div class="article-hero">${visual(a.image,a.category)}</div><div class="article-actions"><button class="btn ghost" data-save="${a.id}">Save</button><button class="btn ghost" data-like="${a.id}">Like</button><button class="btn ghost" data-share="${a.id}">Share</button></div><article class="article-body"><p>${a.subtitle} This article is part of TAISELY’s editorial coverage of technology, energy and the systems shaping what comes next.</p><h2>The central idea</h2><p>Important technology stories are rarely about a single device. They are usually about the interaction between infrastructure, economics, engineering constraints and human behavior. Understanding those layers makes it easier to separate durable change from temporary noise.</p><blockquote>TAISELY focuses on the underlying system, not only the headline.</blockquote><h2>Why it matters</h2><p>When a new capability reaches the real world, the bottlenecks often move. Hardware, energy, distribution, regulation, capital and user experience can all become limiting factors. The result is a longer chain of cause and effect than a headline suggests.</p><h2>What to watch next</h2><p>Look for measurable adoption, falling costs, improving infrastructure and products that solve a recurring problem. Those signals are more useful than novelty alone when thinking about the future.</p></article><section class="related section"><div class="section-head"><h2 class="section-title">Related Articles</h2></div><div class="grid-3">${D.articles.filter(x=>x.id!==a.id&&x.category===a.category).slice(0,3).map(articleCard).join('')}</div></section>`;
    $(`[data-save="${a.id}"]`)?.addEventListener('click',()=>{const s=get('taisely-saved',[]); const has=s.includes(a.id); set('taisely-saved',has?s.filter(x=>x!==a.id):[...s,a.id]); toast(has?'Removed from saved articles.':'Saved article.');});
    $(`[data-like="${a.id}"]`)?.addEventListener('click',()=>{const key='taisely-liked-'+a.id; const liked=localStorage.getItem(key)==='1'; localStorage.setItem(key,liked?'0':'1'); toast(liked?'Like removed.':'Liked.');});
    $(`[data-share="${a.id}"]`)?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Article link copied.')}catch{toast('Copy the URL from the address bar.')}});
  }
  function renderProducts(){
    const grid=$('#product-grid'), cat=$('#product-category'), type=$('#product-type'), search=$('#product-search'); if(!grid)return;
    D.categories.forEach(c=>cat?.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));
    const run=()=>{let arr=[...D.products]; const q=(search?.value||'').toLowerCase(); if(cat?.value)arr=arr.filter(p=>p.category===cat.value); if(type?.value)arr=arr.filter(p=>p.format===type.value); if(q)arr=arr.filter(p=>(p.name+' '+p.desc+' '+p.category).toLowerCase().includes(q)); grid.innerHTML=arr.length?arr.map(productCard).join(''):`<div class="empty">No products match these filters.</div>`;}; [cat,type,search].forEach(el=>el?.addEventListener('input',run)); run();
  }
  function addCart(id,qty=1){const cart=get('taisely-cart',[]); const found=cart.find(i=>i.id===id); if(found)found.qty+=qty; else cart.push({id,qty}); set('taisely-cart',cart); toast('Added to cart.'); renderCartCount();}
  function renderCartCount(){const n=get('taisely-cart',[]).reduce((s,i)=>s+i.qty,0); $$('[data-cart-count]').forEach(e=>e.textContent=n);}
  function renderProduct(){const id=new URLSearchParams(location.search).get('id')||D.products[0].id; const p=D.products.find(x=>x.id===id)||D.products[0]; $('#product-detail').innerHTML=`<div class="gallery">${visual(p.image,p.category)}</div><div class="product-info"><div class="product-type">${p.format}</div><h1>${p.name}</h1><div class="price-large">${money(p.price)}</div><div class="stock">${p.stock?'In stock':'Out of stock'}</div><p class="muted">${p.desc}</p><div class="qty" style="margin:22px 0"><button id="minus">−</button><span id="qty">1</span><button id="plus">+</button></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="add">Add to cart</button><button class="btn ghost" id="buy">Buy now</button></div><div class="rule" style="margin:28px 0"></div><div class="stack"><div><strong>Description</strong><p class="muted">Designed as part of the TAISELY store layer. The production version can connect this product to inventory, payments, shipping and review services without changing the storefront structure.</p></div><div><strong>Specifications</strong><p class="muted">Category: ${p.category}<br>Format: ${p.format}<br>Availability: ${p.stock?'Available':'Unavailable'}</p></div><div><strong>Reviews</strong><p class="muted">Reviews module reserved for authenticated users.</p></div></div></div>`; let qty=1; $('#plus').onclick=()=>{$('#qty').textContent=++qty}; $('#minus').onclick=()=>{$('#qty').textContent=Math.max(1,--qty)}; $('#add').onclick=()=>addCart(p.id,qty); $('#buy').onclick=()=>{addCart(p.id,qty);location.href='cart.html'}; $('#related-products').innerHTML=D.products.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,4).map(productCard).join(''); }
  function renderSearch(){const box=$('#global-search'), wrap=$('#search-results'); const run=()=>{const q=(box.value||'').trim().toLowerCase(); if(!q){wrap.innerHTML='<div class="empty">Search across articles, products and categories.</div>';return;} const ar=D.articles.filter(a=>(a.title+' '+a.subtitle+' '+a.category).toLowerCase().includes(q)).slice(0,8); const pr=D.products.filter(p=>(p.name+' '+p.desc+' '+p.category).toLowerCase().includes(q)).slice(0,8); wrap.innerHTML=[...ar.map(a=>`<a class="result" href="article.html?id=${a.id}">${visual(a.image,a.category)}<div><div class="meta"><span>ARTICLE</span><span>·</span><span>${a.category}</span></div><h3 class="card-title" style="font-size:25px">${a.title}</h3><p class="muted">${a.subtitle}</p></div></a>`),...pr.map(p=>`<a class="result" href="product.html?id=${p.id}">${visual(p.image,p.category)}<div><div class="meta"><span>PRODUCT</span><span>·</span><span>${p.category}</span></div><h3 class="card-title" style="font-size:25px">${p.name}</h3><p class="muted">${p.desc}</p></div></a>`)].join('')||'<div class="empty">No results found.</div>';}; const p=new URLSearchParams(location.search).get('q'); if(p){box.value=p;run()} box?.addEventListener('input',run); $('#search-submit')?.addEventListener('click',run); }
  function renderCart(){const list=$('#cart-items'), sum=$('#cart-summary'); let cart=get('taisely-cart',[]); if(!list)return; const calc=()=>{const lines=cart.map(item=>{const p=D.products.find(x=>x.id===item.id); return p?{...item,p}:{...item,p:null}}).filter(x=>x.p); const subtotal=lines.reduce((s,x)=>s+x.p.price*x.qty,0); const shipping=subtotal?5:0; list.innerHTML=lines.length?lines.map(x=>`<div class="cart-item">${visual(x.p.image,x.p.category)}<div><div class="product-type">${x.p.format}</div><h3 style="margin:4px 0;font-size:19px">${x.p.name}</h3><div class="muted">${money(x.p.price)} each</div><div class="qty" style="margin-top:8px"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div><div class="price-col" style="font-weight:800">${money(x.p.price*x.qty)}<button class="iconbtn" data-remove="${x.id}" style="display:block;margin-top:8px">×</button></div></div>`).join(''):'<div class="empty">Your cart is empty.</div>'; sum.innerHTML=`<h3 style="margin-top:0">Order summary</h3><div class="sumrow"><span>Subtotal</span><span>${money(subtotal)}</span></div><div class="sumrow"><span>Shipping</span><span>${money(shipping)}</span></div><div class="sumrow total"><span>Total</span><span>${money(subtotal+shipping)}</span></div><button class="btn" style="width:100%;margin-top:12px" id="checkout">Checkout</button><p class="muted" style="font-size:12px">Payment is a production integration point; no real charge is made in this demo.</p>`; $$('[data-inc]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.inc);if(x)x.qty++;set('taisely-cart',cart);renderCartCount();calc()}); $$('[data-dec]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.dec);if(x){x.qty=Math.max(1,x.qty-1)}set('taisely-cart',cart);renderCartCount();calc()}); $$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.id!==b.dataset.remove);set('taisely-cart',cart);renderCartCount();calc()}); $('#checkout')?.addEventListener('click',()=>toast('Checkout is reserved for the production backend.'));}; calc(); }
  function renderAccount(){const saved=get('taisely-saved',[]), orders=get('taisely-orders',[]); $('#saved-list').innerHTML=saved.length?D.articles.filter(a=>saved.includes(a.id)).map(articleCard).join(''):'<div class="empty">No saved articles yet.</div>'; $('#orders-list').innerHTML=orders.length?orders.map(o=>`<div class="panel" style="margin-bottom:10px"><strong>Order ${o.id}</strong><div class="muted">${o.date} · ${o.total}</div></div>`).join(''):'<div class="empty">No orders yet.</div>'; $('#demo-login')?.addEventListener('click',()=>toast('Account authentication is a production backend integration point.')); }
  function renderContact(){const f=$('#contact-form');f?.addEventListener('submit',e=>{e.preventDefault();f.reset();toast('Message saved locally for this demo.');});}
  setupGlobal(); renderCartCount(); if(page==='home')renderHome(); if(page==='blog')renderBlog(); if(page==='article')renderArticle(); if(page==='products')renderProducts(); if(page==='product')renderProduct(); if(page==='search')renderSearch(); if(page==='cart')renderCart(); if(page==='account')renderAccount(); if(page==='contact')renderContact();
})();
