window.TAISELY_DATA = {
  categories: ['Technology','Energy','AI','Science','Business','Future'],
  articles: [
    {id:'a1', category:'Technology', type:'News', title:'The next era of personal computing is being built around AI', subtitle:'How on-device intelligence is changing what the everyday computer can do.', author:'TAISELY Editorial', date:'2026-09-21', reading:'6 min', readCount:12840, image:'tech', featured:true},
    {id:'a2', category:'Energy', type:'Explain', title:'Why grid-scale batteries matter more than ever', subtitle:'Storage is becoming the missing layer between renewable generation and reliable electricity.', author:'TAISELY Editorial', date:'2026-09-20', reading:'8 min', readCount:10420, image:'energy'},
    {id:'a3', category:'AI', type:'News', title:'AI agents are moving from chat windows into real workflows', subtitle:'The shift is from answering questions to executing multi-step tasks.', author:'TAISELY Editorial', date:'2026-09-19', reading:'5 min', readCount:9860, image:'ai'},
    {id:'a4', category:'Science', type:'Deep Dive', title:'What astronomers can learn from a planet’s atmosphere', subtitle:'A practical guide to reading worlds you can never physically visit.', author:'TAISELY Editorial', date:'2026-09-18', reading:'12 min', readCount:8310, image:'science'},
    {id:'a5', category:'Business', type:'Explain', title:'The hidden economics behind a successful hardware product', subtitle:'Margins, inventory, distribution and the operational math investors watch.', author:'TAISELY Editorial', date:'2026-09-17', reading:'9 min', readCount:7920, image:'business'},
    {id:'a6', category:'Future', type:'Deep Dive', title:'What happens when energy, compute and transport converge?', subtitle:'Three infrastructure shifts that could reshape the next decade.', author:'TAISELY Editorial', date:'2026-09-16', reading:'14 min', readCount:7540, image:'future'},
    {id:'a7', category:'Technology', type:'Explain', title:'Why semiconductor efficiency is becoming a strategic advantage', subtitle:'More compute is not enough; the cost of moving and cooling it matters too.', author:'TAISELY Editorial', date:'2026-09-15', reading:'7 min', readCount:6880, image:'chips'},
    {id:'a8', category:'Energy', type:'News', title:'Solar hardware is getting easier to deploy at smaller scales', subtitle:'Modular systems are opening new routes for homes, small businesses and remote sites.', author:'TAISELY Editorial', date:'2026-09-14', reading:'5 min', readCount:6420, image:'solar'},
    {id:'a9', category:'AI', type:'Deep Dive', title:'The real bottleneck in AI may be infrastructure, not models', subtitle:'Power, data centers, networking and capital all shape what can be built.', author:'TAISELY Editorial', date:'2026-09-13', reading:'11 min', readCount:6120, image:'datacenter'},
    {id:'a10', category:'Science', type:'Explain', title:'Why deep oceans remain one of Earth’s hardest places to observe', subtitle:'Pressure, darkness and distance create a unique engineering problem.', author:'TAISELY Editorial', date:'2026-09-12', reading:'8 min', readCount:5810, image:'ocean'},
    {id:'a11', category:'Business', type:'News', title:'Why hardware startups are rebuilding their supply chains', subtitle:'Lead times, concentration risk and working capital are changing product strategy.', author:'TAISELY Editorial', date:'2026-09-11', reading:'6 min', readCount:5420, image:'supply'},
    {id:'a12', category:'Future', type:'Explain', title:'The infrastructure logic behind urban electrification', subtitle:'Charging, storage and grid capacity have to scale together.', author:'TAISELY Editorial', date:'2026-09-10', reading:'9 min', readCount:4970, image:'city'},
    {id:'a13', category:'Technology', type:'News', title:'Edge devices are becoming smaller, smarter and more local', subtitle:'A closer look at the push to process more information outside the cloud.', author:'TAISELY Editorial', date:'2026-09-09', reading:'6 min', readCount:4610, image:'edge'},
    {id:'a14', category:'Energy', type:'Deep Dive', title:'What actually makes a battery bank useful?', subtitle:'Capacity, power, cycle life, thermal management and the economics between them.', author:'TAISELY Editorial', date:'2026-09-08', reading:'13 min', readCount:4280, image:'battery'},
    {id:'a15', category:'Future', type:'News', title:'The next industrial shift may be defined by autonomy', subtitle:'Factories, warehouses and transport systems are converging on machine-led operations.', author:'TAISELY Editorial', date:'2026-09-07', reading:'6 min', readCount:3950, image:'robotics'}
  ],
  products: [
    {id:'p1', category:'Energy', name:'TAISELY Grid Battery Guide', price:18, stock:true, format:'Digital Product', image:'battery', desc:'A compact digital field guide to battery systems, capacity, power and storage economics.'},
    {id:'p2', category:'Technology', name:'Future Systems Notepad', price:12, stock:true, format:'Physical Product', image:'notebook', desc:'Minimal A5 notebook built for technical notes, research and systems thinking.'},
    {id:'p3', category:'AI', name:'AI Workflow Starter Pack', price:24, stock:true, format:'Digital Product', image:'ai', desc:'A practical collection of workflow templates for turning AI tools into repeatable systems.'},
    {id:'p4', category:'Energy', name:'Solar Basics Field Sheet', price:9, stock:true, format:'Digital Product', image:'solar', desc:'Visual reference sheets covering solar generation, storage and core system terminology.'},
    {id:'p5', category:'Technology', name:'TAISELY Tech Poster', price:22, stock:true, format:'Physical Product', image:'poster', desc:'Black-and-white editorial poster for a workspace, study room or studio.'},
    {id:'p6', category:'Science', name:'Cosmos Notes PDF', price:14, stock:true, format:'Digital Product', image:'science', desc:'A clean note-taking framework for astronomy, cosmology and scientific reading.'},
    {id:'p7', category:'Future', name:'Future Research Bundle', price:29, stock:true, format:'Digital Product', image:'future', desc:'A structured research bundle for technology, energy, infrastructure and future trends.'},
    {id:'p8', category:'Technology', name:'Data & Systems Cards', price:16, stock:true, format:'Physical Product', image:'cards', desc:'A small deck of prompts for breaking complicated systems into understandable parts.'}
  ]
};
